update (#5)
* drivers/char/tty_buffer.c: Fix distinct type warning

* fs/jfs/super.c: Fix compile warning - 'comparison of distinct pointer types lacks'

* Fix linux-perf-warning

* net/core/filter.c: Fix error: implicit declaration of function 'WARN_RATELIMIT'

* drivers/video/console/cfbcondecor.c: Fix console_missing_argument

* kbuild: fix unused return value from fgets()

* kernel/sched.c: Fix warning: comparison of distinct pointer types lacks a cast