stm: gpio: fix build if CONFIG_BUG is not enabled
On hardened system CONFIG_BUG is not enabled, so __WARN macro is not
defined leading to the following build error:

 CC      drivers/stm/gpio.o
drivers/stm/gpio.c: In function âstm_gpio_get_directionâ:
drivers/stm/gpio.c:654:3: error: implicit declaration of function
â__WARNâ [-Werror=implicit-function-declaration]
   __WARN();
   ^

Fix it by replacing __WARN with WARN_ON(1) that is defined as a nop in
!CONFIG_BUG case.

Reported-by: Philippe Chatel <philippe.chatel@st.com>
Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>
Signed-off-by: persianpros <persianpros@yahoo.com>